# Generated by Django 3.2.5 on 2022-08-09 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0001_initial'),
        ('post', '0003_alter_post_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='group.group'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('user', 'message', 'group')},
        ),
    ]
